apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-template-website
  annotations:
    github.com/project-slug: 'external-spotify-portal-demo/demo-template-website'
spec:
  type: website
  lifecycle: production
  owner: potential-pals
